---

- name: turn swap off
  when: ansible_facts.swaptotal_mb | int > 0
  ansible.builtin.command: swapoff -a


- name: comment out matching references in /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*\sswap\s.*)$'
    replace: '# \1'

- name: activate overlay and br_netfilter in kernel
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - "overlay"
    - "br_netfilter"

- name: enable bridge netfilter and IP forwarding for Kubernetes
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf
    sysctl_set: true
  loop:
    - "net.bridge.bridge-nf-call-iptables"
    - "net.bridge.bridge-nf-call-ip6tables"
    - "net.ipv4.ip_forward"

- name: firewalld configuration
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
    immediate: true
  loop: "{{ k8s_firewall_ports }}"

- name: add Docker CE repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install containerd
  ansible.builtin.dnf:
    name: containerd.io
    state: present

- name: check whether the containerd config has been generated
  ansible.builtin.command: grep -q SystemdCgroup /etc/containerd/config.toml
  register: containerd_config_generated
  changed_when: false
  failed_when: false

- name: create containerd config
  ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
  when: containerd_config_generated.rc != 0
  notify: restart containerd service

- name: configure containerd to use systemd cgroup driver
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*SystemdCgroup\s*=\s*)false'
    replace: '\1true'
  notify: restart containerd service

- name: enable containerd service
  ansible.builtin.systemd:
    name: containerd
    enabled: true
    state: started

- name: add Kubernetes repository
  ansible.builtin.yum_repository:
    name: kubernetes
    description: "Kubernetes {{ k8s_version }}"
    baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/rpm/"
    gpgcheck: true
    gpgkey: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/rpm/repodata/repomd.xml.key"
    exclude: kubelet kubeadm kubectl cri-tools kubernetes-cni

- name: install kubeadm, kubelet and kubectl
  ansible.builtin.dnf:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: kubernetes

- name: enable kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: true

- name: trust kube zone in firewalld
  ansible.posix.firewalld:
    source: "{{ item }}"
    zone: trusted
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ pod_cidr }}"
    - "{{ service_cidr }}"
